### PR TITLE
Fix sed command for BSD version

### PR DESCRIPTION
**Pull request by kbence**
The BSD version of the sed command is slightly different from the GNU version, so let's decide at the beginning which format to use based on the fact that BSD sed doesn't have a --version option.

This might sound a bit hacky, but it's actually more stable than testing for `uname -s` (which will only work for the systems we test for).

Tested with GNU sed on Linux and BSD sed on MacOS.

### CODE REVIEW

**Comment by kbence** [comment]
Execution looks like the following:

<details>
<summary>when executed on macOS</summary>
<pre>
$ make update-version VERSION=9.0.4
# Make sure VERSION is set on the command line "make update-version VERSION=x.y.z".
sed -i '' '1s/.*/VERSION=9.0.4/' event-handler/Makefile
sed -i '' '1s/.*/VERSION=9.0.4/' access/jira/Makefile
sed -i '' '1s/.*/VERSION=9.0.4/' access/mattermost/Makefile
sed -i '' '1s/.*/VERSION=9.0.4/' access/slack/Makefile
sed -i '' '1s/.*/VERSION=9.0.4/' access/pagerduty/Makefile
sed -i '' '1s/.*/VERSION=9.0.4/' access/email/Makefile
sed -i '' '1s/.*/VERSION=9.0.4/' terraform/install.mk
</pre>
</details>

<details>
<summary>when executed on Linux</summary>
<pre>
$  make update-version VERSION=9.0.4
# Make sure VERSION is set on the command line "make update-version VERSION=x.y.z".
sed -i '1s/.*/VERSION=9.0.4/' event-handler/Makefile
sed -i '1s/.*/VERSION=9.0.4/' access/jira/Makefile
sed -i '1s/.*/VERSION=9.0.4/' access/mattermost/Makefile
sed -i '1s/.*/VERSION=9.0.4/' access/slack/Makefile
sed -i '1s/.*/VERSION=9.0.4/' access/pagerduty/Makefile
sed -i '1s/.*/VERSION=9.0.4/' access/email/Makefile
sed -i '1s/.*/VERSION=9.0.4/' terraform/install.mk
</pre>
</details>

**Comment by kbence** [comment]
One change that I can think of would be to rename the variable to `SED_I`, but that looked weird. @logand22, @wadells: what do you think?

**Review by wadells — APPROVED** [review]

**Comment by wadells** [comment]
> One change that I can think of would be to rename the variable to `SED_I`, but that looked weird. @logand22, @wadells: what do you think?

`SED` is fine IMO. The real make patttern would be `SEDFLAGS` in addition to `SED` but that is absolute overkill for our purposes.

**Review by logand22 — APPROVED** [review]
LGTM! Thanks for this!

**Review by tcsc — APPROVED** [review]

**Pull request merged**
