### PR TITLE
Adds disaster recovery tooling for the terraform promotion script

### PR DESCRIPTION
**Pull request by tcsc**
Adds tooling to locally run promotions to the terraform registry in the event of errors in the Drone process.

Expected process looks something like:

```
 $ (cd tooling; go build -o .. ./cmd/with-secrets)
 $ sops -d $plugins_secrets | ./with-secrets ./tooling/bin/release $terraform_provider_version
```

...substituting the appropriate `$plugins_secrets` Drone secrets file and `$terrafom_provider_version` tag (e.g. `terraform-provider-teleport-v9.1.3`)

See `tooling/cmd/with-secrets/main.go` for more info on why `with-secrets` is required.

### CODE REVIEW

**Review by wadells — COMMENTED** [review]
> Expected process looks something like:
>
> ```
>  $ (cd tooling; go build -o .. ./cmd/with-secrets)
>  $ sops -d $plugins_secrets | ./with-secrets ./tooling/bin/release $terraform_provider_version
> ```
>
> ...substituting the appropriate `$plugins_secrets` Drone secrets file and `$terrafom_provider_version` tag (e.g. `terraform-provider-teleport-v9.1.3`)

Could we capture these instructions in a README.md, or maybe RELEASE.md?  I see value in the scripts as a template for how things happen, but I'm concerned without context, only you or I would know what to do with them.

Also: It'd be worth having pointers in both these and the drone logic to each other, to help increase the chance they stay in sync.  I expect updates will get made to one, but not the other eventually.  Anything quick fixes to decrease that likelyhood is time well invested IMO.

**Comment by tcsc** [comment]
> Could we capture these instructions in a README.md, or maybe RELEASE.md

That was my plan. I was trying to figure out where best to put them while this PR was under review. @Joerger - would me just adding a top-level `RELEASE.md` conflict with your #440 at all?

**Comment by wadells** [comment]
> > Could we capture these instructions in a README.md, or maybe RELEASE.md
> 
> That was my plan. I was trying to figure out where best to put them while this PR was under review. @Joerger - would me just adding a top-level `RELEASE.md` conflict with your #440 at all?

Or maybe chuck a commit into `joerger/teleport-plugins-release-strategy`.  I'm ok if that happens in a separate PR.

**Review by wadells — APPROVED** [review]

**Review by Joerger — APPROVED** [review]
Adding a `RELEASE.md` seems useful, if anything I can just add additional notes to it in https://github.com/gravitational/teleport-plugins/pull/440

**Comment by tcsc** [comment]
I've create a bare-bones `RELEASE.md` for now.

**Pull request merged**
