### PR TITLE
Update base docker images

### PR DESCRIPTION
**Pull request by marcoandredinis**
Buddy PR https://github.com/gravitational/teleport-plugins/pull/915

### CODE REVIEW

**Review by strideynet — APPROVED** [review]

**Comment by strideynet** [comment]
Does this also need adjusting in the main Teleport repo for the plugins that have been moved ?

**Comment by marcoandredinis** [comment]
I don't think so.
These are only used for creating the docker images for the plugins.
The ones that were moved live within the teleport binary, and should have their own base docker image.

**Review by reedloden — COMMENTED** [review]
Instead of doing specific hashes, can we just use `gcr.io/distroless/base-debian12`? Specifically, please use a variable at the top of the Dockerfile for easy updating.

Take a look at gravitational/teleport#31620.

**Comment by reedloden** [comment]
> Instead of doing specific hashes, can we just use `gcr.io/distroless/base-debian12`? Specifically, please use a variable at the top of the Dockerfile for easy updating.

I submitted https://github.com/gravitational/teleport-plugins/pull/928 as an alternative to this PR.

**Comment by tcsc** [comment]
We should probably close this in favour of @reedloden's #928.

**Comment by reedloden** [comment]
Addressed in https://github.com/gravitational/teleport-plugins/pull/928.

**Pull request closed without merging**
