### PR TITLE
Updates to RFD 0001

### PR DESCRIPTION
**Pull request by marshall-lee**
- Do some renamings after the code review
- Add a chapter about CRD upgrades

Related to #270 and #319

### CODE REVIEW

**Comment by marshall-lee** [comment]
Shit, for some reason GitHub didn't spot the diff.

@r0mant @pierrebeaucamp what i really is — to review the last chapter about CRD upgrades. There's no more noticeable changes except the renamings.

**Review by Joerger — APPROVED** [review]

**Comment by marcoandredinis** [comment]
@Joerger Can you please take another look?

I removed the Identity resource section
We'll implement that, alongside other resources, later on

**Review by tcsc — APPROVED** [review]

**Pull request merged**
