### PR TITLE
Release 12.4.14

### PR DESCRIPTION
**Pull request by fheinecke**

### CODE REVIEW

**Comment by fheinecke** [comment]
Hey folks I got a weird error upon `make update-version VERSION=12.4.14`. Can reviewers please confirm if this is normal or some kind of regression? I know the discord plugin source was pulled out recent, not sure if related.

```
github.com/gravitational/teleport-plugins/access/discord imports
        github.com/gravitational/teleport/integrations/access/discord: module github.com/gravitational/teleport@latest found (v4.3.10+incompatible, replaced by github.com/gravitational/teleport@v0.0.0-20230803224509-50daf82a2968), but does not contain package github.com/gravitational/teleport/integrations/access/discord
github.com/gravitational/teleport-plugins/access/jira imports
        github.com/gravitational/teleport/integrations/access/jira: module github.com/gravitational/teleport@latest found (v4.3.10+incompatible, replaced by github.com/gravitational/teleport@v0.0.0-20230803224509-50daf82a2968), but does not contain package github.com/gravitational/teleport/integrations/access/jira
github.com/gravitational/teleport-plugins/access/pagerduty imports
        github.com/gravitational/teleport/integrations/access/pagerduty: module github.com/gravitational/teleport@latest found (v4.3.10+incompatible, replaced by github.com/gravitational/teleport@v0.0.0-20230803224509-50daf82a2968), but does not contain package github.com/gravitational/teleport/integrations/access/pagerduty
github.com/gravitational/teleport-plugins/event-handler imports
        github.com/gravitational/teleport/api/gen/proto/go/teleport/auditlog/v1: module github.com/gravitational/teleport/api@latest found (v0.0.0-20230803222018-574b1a9875df, replaced by github.com/gravitational/teleport/api@v0.0.0-20230803224509-50daf82a2968), but does not contain package github.com/gravitational/teleport/api/gen/proto/go/teleport/auditlog/v1
make[1]: *** [update-teleport-dep-version] Error 1
make: *** [update-version] Error 2
```

**Comment by fheinecke** [comment]
This is causing plugin builds to fail as well - what did I screw up?

**Comment by camscale** [comment]
I'm not familiar with what is going on moving the plugin code to the teleport repo, but we do only release plugins alongside the latest branch releases, so it seems odd to me that plugin stuff is backported to v12

**Comment by r0mant** [comment]
We only publish plugins for the latest version.

**Pull request closed without merging**
