### PR TITLE
Making config examples more explicit

### PR DESCRIPTION
**Pull request by benarent**
Helps make https://github.com/gravitational/teleport-plugins/issues/120 clearer, as port mapping can be confusing.

### CODE REVIEW

**Comment by xnutsive** [comment]
I think I had a problem with explicitly putting the port number in slack's public_addr field. Let me test this for a couple plugins and make sure it works as we think it works ;)

**Comment by benarent** [comment]
@xnutsive Did you get a chance to test?

**Comment by xnutsive** [comment]
Nope, but done all the preparation steps. I’ll test tomorrow with the docker flow, and also share the test apps/credentials I’m using.

What’s the best way to store a few secret config so that they’re available to the team? Team 1Password or absolve vault in the repo with a shared password?

Nate
(650) 933-7237

**Comment by benarent** [comment]
I'm going to close this PR as we've made a large amount of progress with the addons.

**Pull request closed without merging**
