### PR TITLE
[Buddy PR] Load identity file from env var

### PR DESCRIPTION
**Pull request by Joerger**
Closes https://github.com/gravitational/teleport-plugins/pull/299 (original PR)

### CODE REVIEW

**Comment by russjones** [comment]
@gzigzigzeo @Joerger Is it intentional that master of Teleport is being vendored? I would expect it to be `branch/v7`?

**Comment by gzigzigzeo** [comment]
@russjones It points to the #8132, otherwise would not work. This reference must be updated once #8132 gets back ported to v7.

**Comment by russjones** [comment]
@Joerger Is this something that can be now be merged?

**Comment by Joerger** [comment]
> @Joerger Is this something that can be now be merged since `teleport/lib` is not longer being imported?

This can be merged as soon as https://github.com/gravitational/teleport/pull/8186 is merged.

**Review by klizhentas — APPROVED** [review]

**Pull request merged**
