### PR TITLE
add dockerfile for building and using slack plugin

### PR DESCRIPTION
**Pull request by khous**
Is there any interest in building and publishing plugins as docker images?
This will make it a lot easier for kubernetes users to use these plugins.

### CODE REVIEW

**Comment by klizhentas** [comment]
@khous great idea, I think we should do it. We'd probably choose a different base image, but otherwise agree 100%

**Comment by klizhentas** [comment]
@webvictim can you give us guidance on what stack we should use for setting up the publishing?

**Comment by khous** [comment]
@klizhentas Thanks for your enthusiasm. What is the preferred base image?

**Comment by klizhentas** [comment]
We'd probably want to keep the image similar to what we use for standard Teleport:

https://github.com/gravitational/teleport/blob/master/build.assets/Dockerfile#L9

**Comment by khous** [comment]
> We'd probably want to keep the image similar to what we use for standard Teleport:
> 
> https://github.com/gravitational/teleport/blob/master/build.assets/Dockerfile#L9

Thanks, I'll take a look

**Comment by webvictim** [comment]
As @klizhentas says we use `ubuntu:18.04` for our Teleport build box (for a lower glibc version requirement on the built binaries) but our [public Teleport images use `ubuntu:20.04` as a base](https://github.com/gravitational/teleport/blob/master/build.assets/charts/Dockerfile).

**Comment by Joerger** [comment]
This is now being handled in https://github.com/gravitational/teleport-plugins/pull/356, thank you for your contribution and suggestion.

**Pull request closed without merging**
