### PR TITLE
Update go to 1.21.0

### PR DESCRIPTION
**Pull request by marcoandredinis**

### CODE REVIEW

**Comment by marcoandredinis** [comment]
Sure, there's no rush :+1:

**Comment by marcoandredinis** [comment]
Converting to draft until branch/v13 gets go 1.21

**Review by tcsc — COMMENTED** [review]
Pre-approval from me, pending update to the `teleport` branch.

**Comment by marcoandredinis** [comment]
Closing this in favor of https://github.com/gravitational/teleport-plugins/pull/910

**Pull request closed without merging**
