### PR TITLE
Pick schema names from json_tag

### PR DESCRIPTION
**Pull request by gzigzigzeo**
I've missed it initially. Users will have to update their configurations.

### CODE REVIEW

**Comment by Joerger** [comment]
> Users will have to update their configurations.

Is this change necessary / what does it accomplish? It'd be best to make this change backwards so that we don't prevent users from updating.

**Comment by gzigzigzeo** [comment]
> Is this change necessary / what does it accomplish? It'd be best to make this change backwards so that we don't prevent users from updating.

I think, it is. This makes output of `tctl get` 1:1 equal to output of `terraform show`. It will help to avoid confusion. For example, for now users have to specify `bpf` in TF config, but will see `enhanced_recording` in `tctl get` output. I think, it's better to eliminate this differences before we have provider released in registry.

**Review by Joerger — APPROVED** [review]

**Review by tcsc — APPROVED** [review]

**Comment by Joerger** [comment]
@gzigzigzeo When is `feature/configuration-entities` going into master? How do you want these PRs that are based on other PRs to be handled? The options I see are to merge multiple PRs with a single buddy Pr, or merge several approved PRs into a single `feature` branch and then make a buddy PR for that feature. I can't tell exactly how this flow has been handled thusfar.

**Comment by gzigzigzeo** [comment]
@Joerger Whatever seems appropriate for you. I think, a single buddy PR is the easiest way.

**Comment by Joerger** [comment]
@gzigzigzeo Can you rebase this PR and #305? You'll need to rebase off master if #325 is merged.

**Comment by gzigzigzeo** [comment]
Sure, let me do it first thing in the morning @Joerger

**Comment by gzigzigzeo** [comment]
@Joerger Awaiting for #325 to be merged

**Comment by Joerger** [comment]
@gzigzigzeo Can you rebase off of #325? I'm not sure how to resolve these merge conflicts myself. And that way I can just cherry pick #304 and #305 once #325 is merged.

**Comment by gzigzigzeo** [comment]
@Joerger Done

**Comment by Joerger** [comment]
@gzigzigzeo Somehow this has conflicts again, sorry but could you rebase again?

**Comment by gzigzigzeo** [comment]
@Joerger done

**Pull request closed without merging**
