### PR TITLE
Drone: test-linux: Fix Terraform install

### LINKED ISSUE #913: `apt-key add` is deprecated
`apt-key add` is deprecated and used in our Drone config.

Instead, `.gpg`/`.asc` files should be placed into `/etc/apt/trusted.gpg.d/` or `/usr/share/keyrings`

Currently, `terraform` installs in Drone seem to fail.

### PR DESCRIPTION
**Pull request by jof**
Fixes #913

### CODE REVIEW

**Review by wadells — APPROVED** [review]
Code LGTM.  How did you test the change?

**Comment by jof** [comment]
> Code LGTM. How did you test the change?

Mostly messing around in a local docker.
I suppose I could try and trigger drone on this branch and see what it does 🤔

**Comment by jof** [comment]
This is less-broken, but it seems like there maybe a broken test that was hiding: https://drone.platform.teleport.sh/gravitational/teleport-plugins/2991/1/3

**Comment by wadells** [comment]
FWIW: I'm good with merging "less broken".  I don't want to make "green" the enemy of "better".

**Review by Joerger — APPROVED** [review]

**Comment by marcoandredinis** [comment]
There's also this PR which has some overlap
https://github.com/gravitational/teleport-plugins/pull/909

**Pull request merged**
